name: scheduled-alert

on:
  schedule:
    - cron: '50 1,2,5,6,7,8 * * 1-5'
jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: use node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: run
        run: |
          npm ci
          npm start
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          ALERT_MESSAGE: ${{ secrets.ALERT_MESSAGE }}
